### PR TITLE
Update in Scrapers

### PR DESCRIPTION
**Pull request by 1UC1F3R616**
- Amazon Scraper Added

### CODE REVIEW

**Comment by 1UC1F3R616** [comment]
@oke-aditya these rename commits have come up again, seems to be an issue with previous squash and merge. If u know some way around then tell else squash and merge this one.

**Comment by 1UC1F3R616** [comment]
- I am working on black code formatting

**Comment by oke-aditya** [comment]
LGTM

**Comment by oke-aditya** [comment]
You didn't merge master into this branch and made changes. Hence it came again.

**Comment by 1UC1F3R616** [comment]
> 
> 
> You didn't merge origin master into this branch and made changes. Hence it came again.

Ok Got it, thanks

**Pull request merged**
